package com.capstone.contractmanagement.utils;

public class MessageKeys {
    public static final String USERNAME_ALREADY_EXISTS = "Tên người dùng đã tồn tại";
    public static final String PHONE_NUMBER_ALREADY_EXISTS = "Số điện thoại đã tồn tại";
    public static final String EMAIL_ALREADY_EXISTS = "Email đã tồn tại";
    public static final String RETRIEVED_ALL_USERS_FAILED = "Lấy danh sách người dùng thất bại";
    public static final String DELETE_USER_SUCCESSFULLY = "Xóa người dùng thành công";
    public static final String UPDATE_USER_SUCCESSFULLY = "Cập nhật người dùng thành công";
    public static final String RETRIEVED_ALL_USERS_SUCCESSFULLY = "Lấy danh sách người dùng thành công";
    public static final String LOGIN_SUCCESSFULLY = "Đăng nhập thành công";
    public static final String REGISTER_SUCCESSFULLY = "Đăng ký thành công";
    public static final String PASSWORD_NOT_MATCH = "Mật khẩu không khớp";
    public static final String USER_IS_LOCKED = "Người dùng đã bị khóa";
    public static final String USER_NOT_FOUND = "Không tìm thấy người dùng";
    public static final String OLD_PASSWORD_WRONG = "Mật khẩu cũ không đúng";
    public static final String CONFIRM_PASSWORD_NOT_MATCH = "Xác nhận mật khẩu không khớp";
    public static final String CHANGE_PASSWORD_SUCCESSFULLY = "Đổi mật khẩu thành công";
    public static final String OTP_SENT_SUCCESSFULLY = "Gửi mã OTP thành công";
    public static final String OTP_IS_EXPIRED = "Mã OTP đã hết hạn";
    public static final String OTP_NOT_FOUND = "Không tìm thấy mã OTP";
    public static final String OTP_VERIFIED_SUCCESSFULLY = "Xác minh OTP thành công";
    public static final String OTP_INCORRECT = "Mã OTP không chính xác";
    public static final String UPDATE_AVATAR_SUCCESSFULLY = "Cập nhật ảnh đại diện thành công";
    public static final String UPLOAD_IMAGES_FILE_MUST_BE_IMAGE = "Tệp tải lên phải là hình ảnh";
    public static final String ROLE_DOES_NOT_EXISTS = "Vai trò không tồn tại";
    public static final String ENABLE_USER_SUCCESSFULLY = "Mở khóa người dùng thành công";
    public static final String BLOCK_USER_SUCCESSFULLY = "Khóa người dùng thành công";
    public static final String NOT_ALLOWED = "Không được phép";
    public static final String TOKEN_GENERATION_FAILED = "Không thể tạo token";
    public static final String CREATE_TERM_SUCCESSFULLY = "Tạo điều khoản thành công";
    public static final String TERM_NOT_FOUND = "Không tìm thấy điều khoản";
    public static final String TYPE_TERM_NOT_FOUND = "Không tìm thấy loại điều khoản";
    public static final String UPDATE_TERM_SUCCESSFULLY = "Cập nhật điều khoản thành công";
    public static final String GET_ALL_TERMS_SUCCESSFULLY = "Lấy danh sách điều khoản thành công";
    public static final String DELETE_TERM_SUCCESSFULLY = "Xóa điều khoản thành công";
    public static final String GET_TERM_SUCCESSFULLY = "Lấy thông tin điều khoản thành công";
    public static final String GET_ALL_TYPE_TERMS_SUCCESSFULLY = "Lấy danh sách loại điều khoản thành công";
    public static final String GET_TYPE_TERM_SUCCESSFULLY = "Lấy thông tin loại điều khoản thành công";
    public static final String CREATE_TASK_SUCCESSFULLY = "Tạo công việc thành công";
    public static final String TASK_NOT_FOUND = "Không tìm thấy công việc";
    public static final String UPDATE_TASK_SUCCESSFULLY = "Cập nhật công việc thành công";
    public static final String DELETE_TASK_SUCCESSFULLY = "Xóa công việc thành công";
    public static final String GET_TASK_SUCCESSFULLY = "Lấy thông tin công việc thành công";
    public static final String SEARCH_TASK_SUCCESSFULLY = "Tìm kiếm công việc thành công";
    public static final String CREATE_TEMPLATE_SUCCESSFULLY = "Tạo mẫu hợp đồng thành công";
    public static final String GET_ALL_TEMPLATES_SUCCESSFULLY = "Lấy danh sách mẫu hợp đồng thành công";
    public static final String GET_TEMPLATE_SUCCESSFULLY = "Lấy thông tin mẫu hợp đồng thành công";
    public static final String DELETE_TEMPLATE_SUCCESSFULLY = "Xóa mẫu hợp đồng thành công";
    public static final String GET_ALL_CONTRACTS_SUCCESSFULLY = "Lấy danh sách hợp đồng thành công";
    public static final String GET_CONTRACT_SUCCESSFULLY = "Lấy thông tin hợp đồng thành công";
    public static final String CREATE_CONTRACT_SUCCESSFULLY = "Tạo hợp đồng thành công";
    public static final String UPDATE_CONTRACT_SUCCESSFULLY = "Cập nhật hợp đồng thành công";
    public static final String DELETE_CONTRACT_SUCCESSFULLY = "Xóa hợp đồng thành công";
    public static final String CREATE_TYPE_TERM_SUCCESSFULLY = "Tạo loại điều khoản thành công";
    public static final String PARTY_NOT_FOUND = "Không tìm thấy đối tác";
    public static final String DELETE_PARTY_SUCCESSFULLY = "Xóa đối tác thành công";
    public static final String CREATE_PARTY_SUCCESSFULLY = "Tạo đối tác thành công";
    public static final String UPDATE_PARTY_SUCCESSFULLY = "Cập nhật đối tác thành công";
    public static final String GET_PARTY_SUCCESSFULLY = "Lấy thông tin đối tác thành công";
    public static final String GET_ALL_PARTIES_SUCCESSFULLY = "Lấy danh sách đối tác thành công";

    public static final String GET_ALL_CONTRACTS_BY_TYPE_SUCCESSFULLY = "Lấy danh sách hợp đồng theo loại thành công";

    public static final String LOGOUT_SUCCESSFULLY = "Đăng xuất thành công";

    public static final String NO_TOKEN_FOUND = "Không tìm thấy token";
    public static final String TOKEN_EXPIRED = "Token hết hạn";
    public static final String TOKEN_INVALID = "Token không hợp lệ";
    public static final String GET_ALL_CONTRACTS_BY_USER_SUCCESSFULLY = "Lấy danh sách hợp đồng theo người dùng thành công";
    public static final String CREATE_PAYMENT_SCHEDULE_SUCCESSFULLY = "Tạo lịch thanh toán hợp đồng thành công";
}
