  services:
    app:
      image: ${BACKEND_IMAGE}
      ports:
        - "8088:8088"
      environment:
        SPRING_PROFILES_ACTIVE: pro
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coms
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      depends_on:
        - db
      networks:
        - backend_network
      volumes:
        - /etc/localtime:/etc/localtime:ro

    db:
      image: postgres:14-alpine # Sử dụng bản Alpine nhẹ hơn
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${DB_PASSWORD} # Sử dụng biến môi trường
        POSTGRES_DB: coms
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - /etc/localtime:/etc/localtime:ro
      networks:
        - backend_network
      deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 1G

  volumes:
    postgres_data:

  networks:
    backend_network:
      internal: true # Chỉ cho phép giao tiếp nội bộ

